### ISSUE TITLE
R60 and rep gains

### ISSUE THREAD

**Issue by DaveB1977** [AraBroker/Ara_Broker_Reputations#4] opened 2022-12-27 13:46 UTC
The fixes you've done are quite frankly amazing, one small niggle is that when you minimise previous expansion reps, and gain any DF rep, all the minimised tabs are opened up again :D

Also, the historical reps have the + next to them, you have to click twice to minimise.

**Comment by mightykong** [comment] 2022-12-27 13:52
Ok, thanks.  I'll take a look at that today.  You're saying that all the reps have a "+" next to them when you gain DF rep after collapsing?  I'll play around with it today and see if I can replicate.

**Comment by mightykong** [comment] 2022-12-27 14:07
This is what I'm seeing.  Can you provide screenshots and some more info?  Like what broker display are you using?  Chocolate, Titan, other?  Have you tried just this addon and the broker display?  It appears to be working in my tests, unless I'm misunderstanding.  What rep gain is causing this?  Tuskar rep didn't seem to cause it.

![SS01](https://user-images.githubusercontent.com/4417339/209677914-ddba2e24-4e51-4f97-94a4-15f67694ad12.png)
![SS02](https://user-images.githubusercontent.com/4417339/209677922-fdf1c747-7c93-4267-b0a2-ce2ff21e5f63.png)
![SS03](https://user-images.githubusercontent.com/4417339/209677935-0074276a-15c2-4a47-8314-ea3552152c3b.png)
![SS04](https://user-images.githubusercontent.com/4417339/209677954-4ff75e4e-122e-4f4a-a23e-88cc07d29686.png)

**Comment by DaveB1977** [comment] 2022-12-27 14:11
![Before](https://user-images.githubusercontent.com/52803773/209676774-0aa52bd5-4643-4a74-bcb8-be44a6a97391.png)
![Rep gain](https://user-images.githubusercontent.com/52803773/209678595-f1ae4a72-52a7-4497-b281-2e8aaa9af5a6.png)

So the "before" is with everything minim,ised, the "rep gain" shows a small rep gain to a DF faction and some older reps re-opneing with the + besdies them

**Comment by DaveB1977** [comment] 2022-12-27 14:12
I noticed it's when you move the mouse away anbd then back over the broker that it happens

**Comment by mightykong** [comment] 2022-12-27 14:19
Paragon rep gains are definitely borked in this scenario, I'll work on that.  But I can't seem to replicate this scenario. Let me try to find some Valdrakken rep.  I'm testing by raising Tuskarr, because it's simple to do, by turning in fish at the fish hole.  I'm wondering if it's due to the fact that Valdrakken is a header as well that's breaking it.  Try doing it on some other non header rep and see if it does the same thing for you.

**Comment by DaveB1977** [comment] 2022-12-27 14:21
It did it whith Tuskarr (cooking) and whatever rep you get from the Seige for me.

**Comment by mightykong** [comment] 2022-12-27 14:29
What broker display are you using?  I don't recognize it and would like to test with it.  Also, any other rep addons?  It looks like something is messing with the IsCollapsed state of the reputation.  This is actually saved as part of the GetFactionInfo(), which is a Blizzard function and not really something in code. I'll go through the code and see if I can find any issues, but it's hard to fix something I can't fully replicate.  

I'll also play with it today with all my reps collapsed and see if anything comes out of it.  If I can't find it, I may put some debugging lines in the code and post a new alpha so you can report back what it's doing.

**Comment by DaveB1977** [comment] 2022-12-27 14:31
I use StatBlockCore as my broker addon, this is the only rep tracking addon I use however I likely have others that trrack rep in a hidden fasion (altoholic, for example)

**Comment by mightykong** [comment] 2022-12-27 14:44
I know it's a pain, but can you try disabling other addons except for this one and StatBlockCore just to eliminate any other interaction?  I'll test with that broker myself today and I'll keep poking at it.  I've put in some debugging code and so far it seems pretty stable maintaining the IsCollapsed state in my setup.  If it is conflicting, if I know what it is conflicting with I can perhaps code around it.

**Comment by mightykong** [comment] 2022-12-27 14:52
Are you using the Sort by Reputation option by chance?  It does look like the reps are sorted alphabetically, but I haven't fixed that code yet.  I put that in the release notes.  If you are using that, I'd turn it off for now.  It's most likely very buggy and I have to go through that code yet.  It's on my list for the beta release.

**Comment by DaveB1977** [comment] 2022-12-27 14:55
Ok, with only SBC and this enabled the rep tracking fine without the expansion of older reps however the double clicking of the + sign persists.

**Comment by mightykong** [comment] 2022-12-27 15:00
Ok, so something else is apparently messing with IsCollapsed() from GetFactionInfo().  I'm getting this state from the Blizzard call, and it is being saved per character in the config on exit and reloading.  But it does always pull it when the table is updated.  The button thing may be related to SBC, I'll load that up and see if I can replicate/fix that after maintenance is done today.

**Comment by DaveB1977** [comment] 2022-12-27 15:08
Ok, I've tracked it down. It looks like Datastore_reputations is the culprit, this is part of the Altoholic addon, with this off the expansion on rep gains goes away

**Comment by mightykong** [comment] 2022-12-27 15:13
Did it also fix the button issue?

**Comment by DaveB1977** [comment] 2022-12-27 15:22
Yes, it looks like both issues are related.

**Comment by DaveB1977** [comment] 2022-12-27 15:49
I think I can safely confirm, after a fair chunk of testing, that the datastore addon is causing the interference.

**Comment by mightykong** [comment] 2022-12-27 16:43
I'll download and take a look at it.  But not sure it's something I can implement a fix for.  I'm just pulling the state from the Blizzard function, so if that addon isn't respecting its state, then not sure what I can do.

**Comment by DaveB1977** [comment] 2022-12-27 16:51
I've put a comment on that addons's page, with a link to this chat, massive thanks in pinning it down!

**Comment by mightykong** [comment] 2022-12-27 16:54
I did find and fix the Paragon session gains for collapsed reps, I'll be pushing an update for that today.

**Comment by mightykong** [comment] 2022-12-27 18:34
Yeah, dug into Altoholic and the isCollapsed treatment.   They're basically forcing open anything that isCollapsed, and then not restoring it to collapsed.  Not quite sure why they're doing that, but that's not something I can deal with.  They need to reset it back to the original state if they're changing it.

`	for i = GetNumFactions(), 1, -1 do		-- 1st pass, expand all categories
		local name, _, _, _, _, _, _,	_, isHeader, isCollapsed = GetFactionInfo(i)
		if isHeader then
			headerCount = headerCount + 1
			if isCollapsed then
				ExpandFactionHeader(i)
				headersState[headerCount] = true
			end
		end
	end`

**Comment by DaveB1977** [comment] 2022-12-27 19:00
Holy crap, nice detective work!! I've added this to my ticket on the altoholic page :)

**Comment by mightykong** [comment] 2022-12-27 19:06
What's happening is that I only update the tablet when a rep changes, so if Altoholic ignores user choice and expands everything, then isCollapsed is not in the same state that Ara knew it to be in when it last updated.  Hence, when you get a rep update, things aren't the way it thought they were when it last updated and it's doing its best to get things back on track.  

I could force it to update more, but that really shouldn't be needed, and that won't fix the crux of the problem is that Altoholic is ignoring user choice to collapse the rep in the first place.

**Comment by mightykong** [comment] 2023-01-02 01:34
Fixed the issue with the buttons, but again, honoring the collapsed state is something that Altoholic needs to stop changing unless the user wants it.

**Closed by mightykong** 2023-01-02 01:34 UTC
